const myArtistsAndImages = [
    {
        id: "01",
        name: "Rembrandt van Rijn",
        descriptionLess: "Rembrandt van Rijn (1606-1669) was born in Leiden, the son of a miller. After finishing Latin School, his parents enrolled him at Leiden University. Rembrandt soon dropped out and became an apprentice painter under Jacob van Swanenburch in Leiden, and later Pieter Lastman in Amsterdam. Back in Leiden, he set up as an independent artist together with Jan Lievens. At this time, Rembrandt mainly painted biblical scenes in a precise style and with vibrant colours.",
        descriptionMore: "In 1631, he moved to Amsterdam where he received numerous commissions for portraits. His many pupils included Ferdinand Bol, Govert Flinck and Carel Fabritius. In this period, Rembrandt develop a more powerful chiaroscuro, a looser brush and a greater sense of drama. He focused more on historical scenes, and made numerous etchings and drawings. In 1634, Rembrandt married Saskia Uylenburgh. They had a son, Titus, in 1641. Then a year later Saskia died. Later, in 1654, Rembrandt had a daughter with Hendrickje Stoffels. By now, he had accumulated huge debts and was forced to sell his house and property. He died in 1669 and was buried in Amsterdam's Westerkerk.",
        imageOne: "/images/The-Night-Watch-Rembrandt.jpg",
        imageOneName: "The Night Watch",
        imageTwo: "/images/Self-portrait-Rembrandt.jpg",
        imageTwoName: "Self portrait",
        imageThree: "/images/Liggende-leeuw-Rembrandt.jpg",
        imageThreeName: "Reclining Lion"
    },
    {
        id: "02",
        name: "Johannes Vermeer",
        descriptionLess: "Today Johannes Vermeer (1632-1675) is one of the most celebrated Dutch 17th century masters. Yet for centuries little importance was attached to his name. Works now known as Vermeers were attributed to other artists. It was only in the 1870s that he was rediscovered and 35 paintings identified as his.",
        descriptionMore: "The son of a silk worker who bought and sold art, Vermeer lived and worked in Delft all his life. He may have served his apprenticeship under fellow townsman Carel Fabritius. In 1653, he joined the local artists guild, which he led at various times. Vermeer’s early paintings of historical scenes reveal the influence of the Utrecht Caravaggists. His later paintings are meticulous compositions of interiors featuring one or two figures, usually women. These are intimate genre paintings in which the subject is engaged in some everyday activity, usually in the light of a nearby window. Vermeer could render the way light plays on objects like few others. The Rijksmuseum has three domestic interiors by Vermeer and one outdoor scene: his world-famous Little Street.",
        imageOne: "/images/The-Milkmaid-Vermeer.jpg",
        imageOneName: "The Milkmaid",
        imageTwo: "/images/Woman-Reading-a-Letter-Vermeer.jpg",
        imageTwoName: "Woman Reading a Letter",
        imageThree: "/images/View-of-Houses-in-Delft-Vermeer.jpg",
        imageThreeName: "View of Houses in Delft, Known as The Little Street"
    },
    {
        id: "03",
        name: "Jan Havicksz. Steen",
        descriptionLess: "Jan Havicksz Steen (ca. 1625-1679) was born in Leiden, the son of a brewer. Educated at a Latin school, in 1646 he enrolled at Leiden university yet never graduated. Instead, he took an apprenticeship as a painter, although little is known about this. Eighteenth-century biographers record that his teachers included Nicolaus Knupfer, Adriaen van Ostade and landscapist Jan van Goyen.",
        descriptionMore: "In 1648, already a master, he helped set up a guild of artists in Leiden, in which he served in various capacities. Steen painted a huge number of works, especially genre paintings showing cheerful people having fun. He also painted portraits, as well as historical scenes. To augment his income, Steen started a brewery in Delft and opened a tavern at his house. Biographers have described him as a man with little sense of restraint, yet that seems to be based more on his paintings than on hard fact. Jan Steen is buried in St Pieter's church in Leiden.",
        imageOne: "/images/The-Merry-Family-Steen.jpg",
        imageOneName: "The Merry Family",
        imageTwo: "/images/The-Feast-of-St-Nicholas-Steen.jpg",
        imageTwoName: "The Feast of St Nicholas",
        imageThree: "/images/Woman-at-her-Toilet-Steen.jpg",
        imageThreeName: "Woman at her Toilet"
    },
    {
        id: "04",
        name: "Hendrick Avercamp",
        descriptionLess: "Born in Amsterdam, Hendrick Avercamp (1585-1634) grew up in Kampen. He lived and worked there from 1614 until his death in 1634. Avercamp is mentioned in various documents as the Kampen Mute, so it is assumed that he was deaf and dumb.",
        descriptionMore: "Avercamp had originally been taught in Amsterdam by Pieter Isacksz, and specialised in winter landscapes. He adopted the Flemish tradition, which was continued in Amsterdam by Gilles van Coninxloo and Pieter Vinckboons. Avercamp's early landscapes have a clear narrative in style, often containing risqué anecdotes. Later, his work acquired a more atmospheric quality.",
        imageOne: "/images/Fishermen-by-Moonlight-Avercamp.jpg",
        imageOneName: "Fishermen by Moonlight",
        imageTwo: "/images/Ice-skating-in-a-Village-Avercamp.jpg",
        imageTwoName: "Ice-skating in a Village",
        imageThree: "/images/Winter-scene-Avercamp.jpg",
        imageThreeName: "Winter scene; a woman and a boy on a small bridge"
    },
    {
        id: "05",
        name: "Hendrick Goltzius",
        descriptionLess: "Draughtsman, engraver and painter Hendrick Goltzius (1558-1617) was born in Mülbracht (now Bracht-am-Niederrhein) in Germany. In 1577, he followed his teacher, printer Dirck Volkertsz Coornhert, to Haarlem. Along with Karel van Mander and Cornelis Cornelisz van Haarlem, Goltzius was part of the Haarlem circle that introduced Mannerist art to the Netherlands.",
        descriptionMore: "Their style is characterised by complex compositions and figures with exaggerated physiques and comparatively small heads. Following a visit to Italy in the 1590s, Goltzius developed a more neoclassical style, with his figures and buildings tending towards classical forms. Goltzius's oeuvre offers an interesting reflection of the changes taking place in Dutch art around 1600. In his day, Goltzius enjoyed an international reputation for the technical brilliance of his engravings.",
        imageOne: "/images/Lot-and-his-Daughters-Goltzius.jpg",
        imageOneName: "Lot and his Daughters",
        imageTwo: "/images/A-Seated-Monkey-on-a-Chain-Goltzius.jpg",
        imageTwoName: "A Seated Monkey on a Chain",
        imageThree: "/images/Neptunus-en-Amphitrite-Goltzius.jpg",
        imageThreeName: "Neptunus en Amphitrite"
    },
    {
        id: "06",
        name: "Jacob Isaacksz. van Ruisdael",
        descriptionLess: "The Haarlem-born painter Jacob van Ruisdael (ca. 1628-1682) began to paint at an early age. His first work dates from 1646. Ruisdael probably had lessons from his father, but his uncle, the artist Salomon van Ruysdael, must also have been a great influence on the young painter. As well as being a painter, Ruisdael was also a doctor. He painted not only woodland landscapes with strong, central motifs such as ruins, watermills and oaks, but also cityscapes and seascapes. Ruisdael's compositions are often more imposing than reality. His 'Bentheim Castle' and 'Windmill at Wijk bij Duurstede' are good examples of this.",
        descriptionMore: "Ruisdael travelled in order to get inspiration for his paintings. On these trips he made many drawings. There are also some etchings which he is known to have made. In the 1650s, probably around 1656, Jacob van Ruisdael moved to Amsterdam, where he lived and worked until his death in 1682.",
        imageOne: "/images/Bentheim-Castle-Ruisdael.jpg",
        imageOneName: "Bentheim Castle",
        imageTwo: "/images/Landscape-with-Waterfall-Ruisdael.jpg",
        imageTwoName: "Landscape with Waterfall",
        imageThree: "/images/The-Windmill-at-Wijk-bij-Duurstede-Ruisdael.jpg",
        imageThreeName: "The Windmill at Wijk bij Duurstede"
    },
    {
        id: "07",
        name: "George Hendrik Breitner",
        descriptionLess: "George Hendrik Breitner (1857-1923) was born in Rotterdam. In 1876, he enrolled at the academy in The Hague. Later, he worked at Willem Maris's studio. In this early period he was especially influenced by the painters of the Hague School. Breitner preferred working-class models: labourers, servant girls and people from lower-class neighbourhoods.",
        descriptionMore: "He saw himself as 'le peintre du peuple', the people's painter. In 1886, he moved to Amsterdam, where he recorded the life of the city in sketches, paintings and photos. Sometimes he made several pictures of the same subject, from different angles or in different weather conditions. Photos might serve as an example for a painting, as for his portraits of girls in kimonos, or as general reference material. Breitner often collaborated with Isaac Israels; both painters are referred to as Amsterdam Impressionists. Conservative critics called Breitner's style 'unfinished'.",
        imageOne: "/images/Girl-in-a-White-Kimono-Breitner.jpg",
        imageOneName: "Girl in a White Kimono",
        imageTwo: "/images/The-Rokin-in-Amsterdam-Breitner.jpg",
        imageTwoName: "The Rokin in Amsterdam",
        imageThree: "/images/The-Yellow-Riders-Breitner.jpg",
        imageThreeName: "The Yellow Riders"
    },
    {
        id: "08",
        name: "Caesar Boëtius van Everdingen",
        descriptionLess: "Caesar Boëtius van Everdingen (1616-1678) was born in Alkmaar. He joined Alkmaar’s St Luke's Guild at a remarkably young age in 1632. From 1641 to 1643 he was living in Amersfoort where he worked under the painter and architect Jacob van Campen.",
        descriptionMore: "In 1648, Van Everdingen moved to Haarlem. He was commissioned by Van Campen to complete two paintings for the Orange hall of the stadholder palace of Huis ten Bosch. In the 1650s, Van Everdingen specialised increasingly in history paintings which he painted in the classical style. In addition to these elevated historical scenes, Van Everdingen also painted genre pieces. By then an affluent man, Van Everdingen returned to Alkmaar in 1657, where he died in 1671. Van Everdingen's younger brother, Allart, was also a painter, mainly known for his landscapes.",
        imageOne: "/images/Girl-in-a-Large-Hat-Everdingen.jpg",
        imageOneName: "Girl in a Large Hat",
        imageTwo: "/images/Pan-and-Syrinx-Everdingen.jpg",
        imageTwoName: "Pan and Syrinx",
        imageThree: "/images/Willem-Jacobsz-Baert-Everdingen.jpg",
        imageThreeName: "Willem Jacobsz Baert (1636-84), Burgomaster of Alkmaar and Amsterdam"
    },
    {
        id: "09",
        name: "9",
        descriptionLess: "",
        descriptionMore: "",
        imageOne: "",
        imageOneName: "",
        imageTwo: "",
        imageTwoName: "",
        imageThree: "",
        imageThreeName: ""
    },
    {
        id: "10",
        name: "10",
        descriptionLess: "",
        descriptionMore: "",
        imageOne: "",
        imageOneName: "",
        imageTwo: "",
        imageTwoName: "",
        imageThree: "",
        imageThreeName: ""
    },
    {
        id: "11",
        name: "11",
        descriptionLess: "",
        descriptionMore: "",
        imageOne: "",
        imageOneName: "",
        imageTwo: "",
        imageTwoName: "",
        imageThree: "",
        imageThreeName: ""
    },
    {
        id: "12",
        name: "12",
        descriptionLess: "",
        descriptionMore: "",
        imageOne: "",
        imageOneName: "",
        imageTwo: "",
        imageTwoName: "",
        imageThree: "",
        imageThreeName: ""
    },
    {
        id: "13",
        name: "13",
        descriptionLess: "",
        descriptionMore: "",
        imageOne: "",
        imageOneName: "",
        imageTwo: "",
        imageTwoName: "",
        imageThree: "",
        imageThreeName: ""
    },
    {
        id: "14",
        name: "14",
        descriptionLess: "",
        descriptionMore: "",
        imageOne: "",
        imageOneName: "",
        imageTwo: "",
        imageTwoName: "",
        imageThree: "",
        imageThreeName: ""
    },
    {
        id: "15",
        name: "15",
        descriptionLess: "",
        descriptionMore: "",
        imageOne: "",
        imageOneName: "",
        imageTwo: "",
        imageTwoName: "",
        imageThree: "",
        imageThreeName: ""
    },
    {
        id: "16",
        name: "16",
        descriptionLess: "",
        descriptionMore: "",
        imageOne: "",
        imageOneName: "",
        imageTwo: "",
        imageTwoName: "",
        imageThree: "",
        imageThreeName: ""
    },
    {
        id: "17",
        name: "17",
        descriptionLess: "",
        descriptionMore: "",
        imageOne: "",
        imageOneName: "",
        imageTwo: "",
        imageTwoName: "",
        imageThree: "",
        imageThreeName: ""
    },
    {
        id: "18",
        name: "18",
        descriptionLess: "",
        descriptionMore: "",
        imageOne: "",
        imageOneName: "",
        imageTwo: "",
        imageTwoName: "",
        imageThree: "",
        imageThreeName: ""
    },
    {
        id: "19",
        name: "19",
        descriptionLess: "",
        descriptionMore: "",
        imageOne: "",
        imageOneName: "",
        imageTwo: "",
        imageTwoName: "",
        imageThree: "",
        imageThreeName: ""
    },
    {
        id: "20",
        name: "20",
        descriptionLess: "",
        descriptionMore: "",
        imageOne: "",
        imageOneName: "",
        imageTwo: "",
        imageTwoName: "",
        imageThree: "",
        imageThreeName: ""
    },
    {
        id: "21",
        name: "21",
        descriptionLess: "",
        descriptionMore: "",
        imageOne: "",
        imageOneName: "",
        imageTwo: "",
        imageTwoName: "",
        imageThree: "",
        imageThreeName: ""
    },
    {
        id: "22",
        name: "",
        descriptionLess: "",
        descriptionMore: "",
        imageOne: "",
        imageOneName: "",
        imageTwo: "",
        imageTwoName: "",
        imageThree: "",
        imageThreeName: ""
    },
    {
        id: "23",
        name: "",
        descriptionLess: "",
        descriptionMore: "",
        imageOne: "",
        imageOneName: "",
        imageTwo: "",
        imageTwoName: "",
        imageThree: "",
        imageThreeName: ""
    },
    {
        id: "24",
        name: "",
        descriptionLess: "",
        descriptionMore: "",
        imageOne: "",
        imageOneName: "",
        imageTwo: "",
        imageTwoName: "",
        imageThree: "",
        imageThreeName: ""
    },
    {
        id: "25",
        name: "",
        descriptionLess: "",
        descriptionMore: "",
        imageOne: "",
        imageOneName: "",
        imageTwo: "",
        imageTwoName: "",
        imageThree: "",
        imageThreeName: ""
    }
]


