const myArtistsAndImages = [
    {
        name: "Rembrandt van Rijn",
        descriptionLess: "Rembrandt van Rijn (1606-1669) was born in Leiden, the son of a miller. After finishing Latin School, his parents enrolled him at Leiden University. Rembrandt soon dropped out and became an apprentice painter under Jacob van Swanenburch in Leiden, and later Pieter Lastman in Amsterdam. Back in Leiden, he set up as an independent artist together with Jan Lievens. At this time, Rembrandt mainly painted biblical scenes in a precise style and with vibrant colours.",
        descriptionMore: "In 1631, he moved to Amsterdam where he received numerous commissions for portraits. His many pupils included Ferdinand Bol, Govert Flinck and Carel Fabritius. In this period, Rembrandt develop a more powerful chiaroscuro, a looser brush and a greater sense of drama. He focused more on historical scenes, and made numerous etchings and drawings. In 1634, Rembrandt married Saskia Uylenburgh. They had a son, Titus, in 1641. Then a year later Saskia died. Later, in 1654, Rembrandt had a daughter with Hendrickje Stoffels. By now, he had accumulated huge debts and was forced to sell his house and property. He died in 1669 and was buried in Amsterdam's Westerkerk.",
        imageOne: "/images/The-Night-Watch-Rembrandt.jpg",
        imageOneName: "The Night Watch",
        imageTwo: "/images/Self-portrait-Rembrandt.jpg",
        imageTwoName: "Self portrait",
        imageThree: "/images/Liggende-leeuw-Rembrandt.jpg",
        imageThreeName: "Liggende leeuw"
    },
    {
        name: "Rembrandt van Rijn",
        descriptionLess: "Rembrandt van Rijn (1606-1669) was born in Leiden, the son of a miller. After finishing Latin School, his parents enrolled him at Leiden University. Rembrandt soon dropped out and became an apprentice painter under Jacob van Swanenburch in Leiden, and later Pieter Lastman in Amsterdam. Back in Leiden, he set up as an independent artist together with Jan Lievens. At this time, Rembrandt mainly painted biblical scenes in a precise style and with vibrant colours.",
        descriptionMore: "In 1631, he moved to Amsterdam where he received numerous commissions for portraits. His many pupils included Ferdinand Bol, Govert Flinck and Carel Fabritius. In this period, Rembrandt develop a more powerful chiaroscuro, a looser brush and a greater sense of drama. He focused more on historical scenes, and made numerous etchings and drawings. In 1634, Rembrandt married Saskia Uylenburgh. They had a son, Titus, in 1641. Then a year later Saskia died. Later, in 1654, Rembrandt had a daughter with Hendrickje Stoffels. By now, he had accumulated huge debts and was forced to sell his house and property. He died in 1669 and was buried in Amsterdam's Westerkerk.",
        imageOne: "/images/The-Night-Watch-Rembrandt.jpg",
        imageOneName: "The Night Watch",
        imageTwo: "/images/Self-portrait-Rembrandt.jpg",
        imageTwoName: "Self portrait",
        imageThree: "/images/Liggende-leeuw-Rembrandt.jpg",
        imageThreeName: "Liggende leeuw"
    },
    {
        name: "Rembrandt van Rijn",
        descriptionLess: "Rembrandt van Rijn (1606-1669) was born in Leiden, the son of a miller. After finishing Latin School, his parents enrolled him at Leiden University. Rembrandt soon dropped out and became an apprentice painter under Jacob van Swanenburch in Leiden, and later Pieter Lastman in Amsterdam. Back in Leiden, he set up as an independent artist together with Jan Lievens. At this time, Rembrandt mainly painted biblical scenes in a precise style and with vibrant colours.",
        descriptionMore: "In 1631, he moved to Amsterdam where he received numerous commissions for portraits. His many pupils included Ferdinand Bol, Govert Flinck and Carel Fabritius. In this period, Rembrandt develop a more powerful chiaroscuro, a looser brush and a greater sense of drama. He focused more on historical scenes, and made numerous etchings and drawings. In 1634, Rembrandt married Saskia Uylenburgh. They had a son, Titus, in 1641. Then a year later Saskia died. Later, in 1654, Rembrandt had a daughter with Hendrickje Stoffels. By now, he had accumulated huge debts and was forced to sell his house and property. He died in 1669 and was buried in Amsterdam's Westerkerk.",
        imageOne: "/images/The-Night-Watch-Rembrandt.jpg",
        imageOneName: "The Night Watch",
        imageTwo: "/images/Self-portrait-Rembrandt.jpg",
        imageTwoName: "Self portrait",
        imageThree: "/images/Liggende-leeuw-Rembrandt.jpg",
        imageThreeName: "Liggende leeuw"
    },
    {
        name: "Rembrandt van Rijn",
        descriptionLess: "Rembrandt van Rijn (1606-1669) was born in Leiden, the son of a miller. After finishing Latin School, his parents enrolled him at Leiden University. Rembrandt soon dropped out and became an apprentice painter under Jacob van Swanenburch in Leiden, and later Pieter Lastman in Amsterdam. Back in Leiden, he set up as an independent artist together with Jan Lievens. At this time, Rembrandt mainly painted biblical scenes in a precise style and with vibrant colours.",
        descriptionMore: "In 1631, he moved to Amsterdam where he received numerous commissions for portraits. His many pupils included Ferdinand Bol, Govert Flinck and Carel Fabritius. In this period, Rembrandt develop a more powerful chiaroscuro, a looser brush and a greater sense of drama. He focused more on historical scenes, and made numerous etchings and drawings. In 1634, Rembrandt married Saskia Uylenburgh. They had a son, Titus, in 1641. Then a year later Saskia died. Later, in 1654, Rembrandt had a daughter with Hendrickje Stoffels. By now, he had accumulated huge debts and was forced to sell his house and property. He died in 1669 and was buried in Amsterdam's Westerkerk.",
        imageOne: "/images/The-Night-Watch-Rembrandt.jpg",
        imageOneName: "The Night Watch",
        imageTwo: "/images/Self-portrait-Rembrandt.jpg",
        imageTwoName: "Self portrait",
        imageThree: "/images/Liggende-leeuw-Rembrandt.jpg",
        imageThreeName: "Liggende leeuw"
    },
    {
        name: "Rembrandt van Rijn",
        descriptionLess: "Rembrandt van Rijn (1606-1669) was born in Leiden, the son of a miller. After finishing Latin School, his parents enrolled him at Leiden University. Rembrandt soon dropped out and became an apprentice painter under Jacob van Swanenburch in Leiden, and later Pieter Lastman in Amsterdam. Back in Leiden, he set up as an independent artist together with Jan Lievens. At this time, Rembrandt mainly painted biblical scenes in a precise style and with vibrant colours.",
        descriptionMore: "In 1631, he moved to Amsterdam where he received numerous commissions for portraits. His many pupils included Ferdinand Bol, Govert Flinck and Carel Fabritius. In this period, Rembrandt develop a more powerful chiaroscuro, a looser brush and a greater sense of drama. He focused more on historical scenes, and made numerous etchings and drawings. In 1634, Rembrandt married Saskia Uylenburgh. They had a son, Titus, in 1641. Then a year later Saskia died. Later, in 1654, Rembrandt had a daughter with Hendrickje Stoffels. By now, he had accumulated huge debts and was forced to sell his house and property. He died in 1669 and was buried in Amsterdam's Westerkerk.",
        imageOne: "/images/The-Night-Watch-Rembrandt.jpg",
        imageOneName: "The Night Watch",
        imageTwo: "/images/Self-portrait-Rembrandt.jpg",
        imageTwoName: "Self portrait",
        imageThree: "/images/Liggende-leeuw-Rembrandt.jpg",
        imageThreeName: "Liggende leeuw"
    },
    {
        name: "Rembrandt van Rijn",
        descriptionLess: "Rembrandt van Rijn (1606-1669) was born in Leiden, the son of a miller. After finishing Latin School, his parents enrolled him at Leiden University. Rembrandt soon dropped out and became an apprentice painter under Jacob van Swanenburch in Leiden, and later Pieter Lastman in Amsterdam. Back in Leiden, he set up as an independent artist together with Jan Lievens. At this time, Rembrandt mainly painted biblical scenes in a precise style and with vibrant colours.",
        descriptionMore: "In 1631, he moved to Amsterdam where he received numerous commissions for portraits. His many pupils included Ferdinand Bol, Govert Flinck and Carel Fabritius. In this period, Rembrandt develop a more powerful chiaroscuro, a looser brush and a greater sense of drama. He focused more on historical scenes, and made numerous etchings and drawings. In 1634, Rembrandt married Saskia Uylenburgh. They had a son, Titus, in 1641. Then a year later Saskia died. Later, in 1654, Rembrandt had a daughter with Hendrickje Stoffels. By now, he had accumulated huge debts and was forced to sell his house and property. He died in 1669 and was buried in Amsterdam's Westerkerk.",
        imageOne: "/images/The-Night-Watch-Rembrandt.jpg",
        imageOneName: "The Night Watch",
        imageTwo: "/images/Self-portrait-Rembrandt.jpg",
        imageTwoName: "Self portrait",
        imageThree: "/images/Liggende-leeuw-Rembrandt.jpg",
        imageThreeName: "Liggende leeuw"
    },
    {
        name: "Rembrandt van Rijn",
        descriptionLess: "Rembrandt van Rijn (1606-1669) was born in Leiden, the son of a miller. After finishing Latin School, his parents enrolled him at Leiden University. Rembrandt soon dropped out and became an apprentice painter under Jacob van Swanenburch in Leiden, and later Pieter Lastman in Amsterdam. Back in Leiden, he set up as an independent artist together with Jan Lievens. At this time, Rembrandt mainly painted biblical scenes in a precise style and with vibrant colours.",
        descriptionMore: "In 1631, he moved to Amsterdam where he received numerous commissions for portraits. His many pupils included Ferdinand Bol, Govert Flinck and Carel Fabritius. In this period, Rembrandt develop a more powerful chiaroscuro, a looser brush and a greater sense of drama. He focused more on historical scenes, and made numerous etchings and drawings. In 1634, Rembrandt married Saskia Uylenburgh. They had a son, Titus, in 1641. Then a year later Saskia died. Later, in 1654, Rembrandt had a daughter with Hendrickje Stoffels. By now, he had accumulated huge debts and was forced to sell his house and property. He died in 1669 and was buried in Amsterdam's Westerkerk.",
        imageOne: "/images/The-Night-Watch-Rembrandt.jpg",
        imageOneName: "The Night Watch",
        imageTwo: "/images/Self-portrait-Rembrandt.jpg",
        imageTwoName: "Self portrait",
        imageThree: "/images/Liggende-leeuw-Rembrandt.jpg",
        imageThreeName: "Liggende leeuw"
    },
    {
        name: "Rembrandt van Rijn",
        descriptionLess: "Rembrandt van Rijn (1606-1669) was born in Leiden, the son of a miller. After finishing Latin School, his parents enrolled him at Leiden University. Rembrandt soon dropped out and became an apprentice painter under Jacob van Swanenburch in Leiden, and later Pieter Lastman in Amsterdam. Back in Leiden, he set up as an independent artist together with Jan Lievens. At this time, Rembrandt mainly painted biblical scenes in a precise style and with vibrant colours.",
        descriptionMore: "In 1631, he moved to Amsterdam where he received numerous commissions for portraits. His many pupils included Ferdinand Bol, Govert Flinck and Carel Fabritius. In this period, Rembrandt develop a more powerful chiaroscuro, a looser brush and a greater sense of drama. He focused more on historical scenes, and made numerous etchings and drawings. In 1634, Rembrandt married Saskia Uylenburgh. They had a son, Titus, in 1641. Then a year later Saskia died. Later, in 1654, Rembrandt had a daughter with Hendrickje Stoffels. By now, he had accumulated huge debts and was forced to sell his house and property. He died in 1669 and was buried in Amsterdam's Westerkerk.",
        imageOne: "/images/The-Night-Watch-Rembrandt.jpg",
        imageOneName: "The Night Watch",
        imageTwo: "/images/Self-portrait-Rembrandt.jpg",
        imageTwoName: "Self portrait",
        imageThree: "/images/Liggende-leeuw-Rembrandt.jpg",
        imageThreeName: "Liggende leeuw"
    },
    {
        name: "Rembrandt van Rijn",
        descriptionLess: "Rembrandt van Rijn (1606-1669) was born in Leiden, the son of a miller. After finishing Latin School, his parents enrolled him at Leiden University. Rembrandt soon dropped out and became an apprentice painter under Jacob van Swanenburch in Leiden, and later Pieter Lastman in Amsterdam. Back in Leiden, he set up as an independent artist together with Jan Lievens. At this time, Rembrandt mainly painted biblical scenes in a precise style and with vibrant colours.",
        descriptionMore: "In 1631, he moved to Amsterdam where he received numerous commissions for portraits. His many pupils included Ferdinand Bol, Govert Flinck and Carel Fabritius. In this period, Rembrandt develop a more powerful chiaroscuro, a looser brush and a greater sense of drama. He focused more on historical scenes, and made numerous etchings and drawings. In 1634, Rembrandt married Saskia Uylenburgh. They had a son, Titus, in 1641. Then a year later Saskia died. Later, in 1654, Rembrandt had a daughter with Hendrickje Stoffels. By now, he had accumulated huge debts and was forced to sell his house and property. He died in 1669 and was buried in Amsterdam's Westerkerk.",
        imageOne: "/images/The-Night-Watch-Rembrandt.jpg",
        imageOneName: "The Night Watch",
        imageTwo: "/images/Self-portrait-Rembrandt.jpg",
        imageTwoName: "Self portrait",
        imageThree: "/images/Liggende-leeuw-Rembrandt.jpg",
        imageThreeName: "Liggende leeuw"
    },
    {
        name: "Rembrandt van Rijn",
        descriptionLess: "Rembrandt van Rijn (1606-1669) was born in Leiden, the son of a miller. After finishing Latin School, his parents enrolled him at Leiden University. Rembrandt soon dropped out and became an apprentice painter under Jacob van Swanenburch in Leiden, and later Pieter Lastman in Amsterdam. Back in Leiden, he set up as an independent artist together with Jan Lievens. At this time, Rembrandt mainly painted biblical scenes in a precise style and with vibrant colours.",
        descriptionMore: "In 1631, he moved to Amsterdam where he received numerous commissions for portraits. His many pupils included Ferdinand Bol, Govert Flinck and Carel Fabritius. In this period, Rembrandt develop a more powerful chiaroscuro, a looser brush and a greater sense of drama. He focused more on historical scenes, and made numerous etchings and drawings. In 1634, Rembrandt married Saskia Uylenburgh. They had a son, Titus, in 1641. Then a year later Saskia died. Later, in 1654, Rembrandt had a daughter with Hendrickje Stoffels. By now, he had accumulated huge debts and was forced to sell his house and property. He died in 1669 and was buried in Amsterdam's Westerkerk.",
        imageOne: "/images/The-Night-Watch-Rembrandt.jpg",
        imageOneName: "The Night Watch",
        imageTwo: "/images/Self-portrait-Rembrandt.jpg",
        imageTwoName: "Self portrait",
        imageThree: "/images/Liggende-leeuw-Rembrandt.jpg",
        imageThreeName: "Liggende leeuw"
    },
    {
        name: "Rembrandt van Rijn",
        descriptionLess: "Rembrandt van Rijn (1606-1669) was born in Leiden, the son of a miller. After finishing Latin School, his parents enrolled him at Leiden University. Rembrandt soon dropped out and became an apprentice painter under Jacob van Swanenburch in Leiden, and later Pieter Lastman in Amsterdam. Back in Leiden, he set up as an independent artist together with Jan Lievens. At this time, Rembrandt mainly painted biblical scenes in a precise style and with vibrant colours.",
        descriptionMore: "In 1631, he moved to Amsterdam where he received numerous commissions for portraits. His many pupils included Ferdinand Bol, Govert Flinck and Carel Fabritius. In this period, Rembrandt develop a more powerful chiaroscuro, a looser brush and a greater sense of drama. He focused more on historical scenes, and made numerous etchings and drawings. In 1634, Rembrandt married Saskia Uylenburgh. They had a son, Titus, in 1641. Then a year later Saskia died. Later, in 1654, Rembrandt had a daughter with Hendrickje Stoffels. By now, he had accumulated huge debts and was forced to sell his house and property. He died in 1669 and was buried in Amsterdam's Westerkerk.",
        imageOne: "/images/The-Night-Watch-Rembrandt.jpg",
        imageOneName: "The Night Watch",
        imageTwo: "/images/Self-portrait-Rembrandt.jpg",
        imageTwoName: "Self portrait",
        imageThree: "/images/Liggende-leeuw-Rembrandt.jpg",
        imageThreeName: "Liggende leeuw"
    },
    {
        name: "Rembrandt van Rijn",
        descriptionLess: "Rembrandt van Rijn (1606-1669) was born in Leiden, the son of a miller. After finishing Latin School, his parents enrolled him at Leiden University. Rembrandt soon dropped out and became an apprentice painter under Jacob van Swanenburch in Leiden, and later Pieter Lastman in Amsterdam. Back in Leiden, he set up as an independent artist together with Jan Lievens. At this time, Rembrandt mainly painted biblical scenes in a precise style and with vibrant colours.",
        descriptionMore: "In 1631, he moved to Amsterdam where he received numerous commissions for portraits. His many pupils included Ferdinand Bol, Govert Flinck and Carel Fabritius. In this period, Rembrandt develop a more powerful chiaroscuro, a looser brush and a greater sense of drama. He focused more on historical scenes, and made numerous etchings and drawings. In 1634, Rembrandt married Saskia Uylenburgh. They had a son, Titus, in 1641. Then a year later Saskia died. Later, in 1654, Rembrandt had a daughter with Hendrickje Stoffels. By now, he had accumulated huge debts and was forced to sell his house and property. He died in 1669 and was buried in Amsterdam's Westerkerk.",
        imageOne: "/images/The-Night-Watch-Rembrandt.jpg",
        imageOneName: "The Night Watch",
        imageTwo: "/images/Self-portrait-Rembrandt.jpg",
        imageTwoName: "Self portrait",
        imageThree: "/images/Liggende-leeuw-Rembrandt.jpg",
        imageThreeName: "Liggende leeuw"
    },
    {
        name: "Rembrandt van Rijn",
        descriptionLess: "Rembrandt van Rijn (1606-1669) was born in Leiden, the son of a miller. After finishing Latin School, his parents enrolled him at Leiden University. Rembrandt soon dropped out and became an apprentice painter under Jacob van Swanenburch in Leiden, and later Pieter Lastman in Amsterdam. Back in Leiden, he set up as an independent artist together with Jan Lievens. At this time, Rembrandt mainly painted biblical scenes in a precise style and with vibrant colours.",
        descriptionMore: "In 1631, he moved to Amsterdam where he received numerous commissions for portraits. His many pupils included Ferdinand Bol, Govert Flinck and Carel Fabritius. In this period, Rembrandt develop a more powerful chiaroscuro, a looser brush and a greater sense of drama. He focused more on historical scenes, and made numerous etchings and drawings. In 1634, Rembrandt married Saskia Uylenburgh. They had a son, Titus, in 1641. Then a year later Saskia died. Later, in 1654, Rembrandt had a daughter with Hendrickje Stoffels. By now, he had accumulated huge debts and was forced to sell his house and property. He died in 1669 and was buried in Amsterdam's Westerkerk.",
        imageOne: "/images/The-Night-Watch-Rembrandt.jpg",
        imageOneName: "The Night Watch",
        imageTwo: "/images/Self-portrait-Rembrandt.jpg",
        imageTwoName: "Self portrait",
        imageThree: "/images/Liggende-leeuw-Rembrandt.jpg",
        imageThreeName: "Liggende leeuw"
    },
    {
        name: "Rembrandt van Rijn",
        descriptionLess: "Rembrandt van Rijn (1606-1669) was born in Leiden, the son of a miller. After finishing Latin School, his parents enrolled him at Leiden University. Rembrandt soon dropped out and became an apprentice painter under Jacob van Swanenburch in Leiden, and later Pieter Lastman in Amsterdam. Back in Leiden, he set up as an independent artist together with Jan Lievens. At this time, Rembrandt mainly painted biblical scenes in a precise style and with vibrant colours.",
        descriptionMore: "In 1631, he moved to Amsterdam where he received numerous commissions for portraits. His many pupils included Ferdinand Bol, Govert Flinck and Carel Fabritius. In this period, Rembrandt develop a more powerful chiaroscuro, a looser brush and a greater sense of drama. He focused more on historical scenes, and made numerous etchings and drawings. In 1634, Rembrandt married Saskia Uylenburgh. They had a son, Titus, in 1641. Then a year later Saskia died. Later, in 1654, Rembrandt had a daughter with Hendrickje Stoffels. By now, he had accumulated huge debts and was forced to sell his house and property. He died in 1669 and was buried in Amsterdam's Westerkerk.",
        imageOne: "/images/The-Night-Watch-Rembrandt.jpg",
        imageOneName: "The Night Watch",
        imageTwo: "/images/Self-portrait-Rembrandt.jpg",
        imageTwoName: "Self portrait",
        imageThree: "/images/Liggende-leeuw-Rembrandt.jpg",
        imageThreeName: "Liggende leeuw"
    },
    {
        name: "Rembrandt van Rijn",
        descriptionLess: "Rembrandt van Rijn (1606-1669) was born in Leiden, the son of a miller. After finishing Latin School, his parents enrolled him at Leiden University. Rembrandt soon dropped out and became an apprentice painter under Jacob van Swanenburch in Leiden, and later Pieter Lastman in Amsterdam. Back in Leiden, he set up as an independent artist together with Jan Lievens. At this time, Rembrandt mainly painted biblical scenes in a precise style and with vibrant colours.",
        descriptionMore: "In 1631, he moved to Amsterdam where he received numerous commissions for portraits. His many pupils included Ferdinand Bol, Govert Flinck and Carel Fabritius. In this period, Rembrandt develop a more powerful chiaroscuro, a looser brush and a greater sense of drama. He focused more on historical scenes, and made numerous etchings and drawings. In 1634, Rembrandt married Saskia Uylenburgh. They had a son, Titus, in 1641. Then a year later Saskia died. Later, in 1654, Rembrandt had a daughter with Hendrickje Stoffels. By now, he had accumulated huge debts and was forced to sell his house and property. He died in 1669 and was buried in Amsterdam's Westerkerk.",
        imageOne: "/images/The-Night-Watch-Rembrandt.jpg",
        imageOneName: "The Night Watch",
        imageTwo: "/images/Self-portrait-Rembrandt.jpg",
        imageTwoName: "Self portrait",
        imageThree: "/images/Liggende-leeuw-Rembrandt.jpg",
        imageThreeName: "Liggende leeuw"
    },
    {
        name: "Rembrandt van Rijn",
        descriptionLess: "Rembrandt van Rijn (1606-1669) was born in Leiden, the son of a miller. After finishing Latin School, his parents enrolled him at Leiden University. Rembrandt soon dropped out and became an apprentice painter under Jacob van Swanenburch in Leiden, and later Pieter Lastman in Amsterdam. Back in Leiden, he set up as an independent artist together with Jan Lievens. At this time, Rembrandt mainly painted biblical scenes in a precise style and with vibrant colours.",
        descriptionMore: "In 1631, he moved to Amsterdam where he received numerous commissions for portraits. His many pupils included Ferdinand Bol, Govert Flinck and Carel Fabritius. In this period, Rembrandt develop a more powerful chiaroscuro, a looser brush and a greater sense of drama. He focused more on historical scenes, and made numerous etchings and drawings. In 1634, Rembrandt married Saskia Uylenburgh. They had a son, Titus, in 1641. Then a year later Saskia died. Later, in 1654, Rembrandt had a daughter with Hendrickje Stoffels. By now, he had accumulated huge debts and was forced to sell his house and property. He died in 1669 and was buried in Amsterdam's Westerkerk.",
        imageOne: "/images/The-Night-Watch-Rembrandt.jpg",
        imageOneName: "The Night Watch",
        imageTwo: "/images/Self-portrait-Rembrandt.jpg",
        imageTwoName: "Self portrait",
        imageThree: "/images/Liggende-leeuw-Rembrandt.jpg",
        imageThreeName: "Liggende leeuw"
    },
    {
        name: "Rembrandt van Rijn",
        descriptionLess: "Rembrandt van Rijn (1606-1669) was born in Leiden, the son of a miller. After finishing Latin School, his parents enrolled him at Leiden University. Rembrandt soon dropped out and became an apprentice painter under Jacob van Swanenburch in Leiden, and later Pieter Lastman in Amsterdam. Back in Leiden, he set up as an independent artist together with Jan Lievens. At this time, Rembrandt mainly painted biblical scenes in a precise style and with vibrant colours.",
        descriptionMore: "In 1631, he moved to Amsterdam where he received numerous commissions for portraits. His many pupils included Ferdinand Bol, Govert Flinck and Carel Fabritius. In this period, Rembrandt develop a more powerful chiaroscuro, a looser brush and a greater sense of drama. He focused more on historical scenes, and made numerous etchings and drawings. In 1634, Rembrandt married Saskia Uylenburgh. They had a son, Titus, in 1641. Then a year later Saskia died. Later, in 1654, Rembrandt had a daughter with Hendrickje Stoffels. By now, he had accumulated huge debts and was forced to sell his house and property. He died in 1669 and was buried in Amsterdam's Westerkerk.",
        imageOne: "/images/The-Night-Watch-Rembrandt.jpg",
        imageOneName: "The Night Watch",
        imageTwo: "/images/Self-portrait-Rembrandt.jpg",
        imageTwoName: "Self portrait",
        imageThree: "/images/Liggende-leeuw-Rembrandt.jpg",
        imageThreeName: "Liggende leeuw"
    },
    {
        name: "Rembrandt van Rijn",
        descriptionLess: "Rembrandt van Rijn (1606-1669) was born in Leiden, the son of a miller. After finishing Latin School, his parents enrolled him at Leiden University. Rembrandt soon dropped out and became an apprentice painter under Jacob van Swanenburch in Leiden, and later Pieter Lastman in Amsterdam. Back in Leiden, he set up as an independent artist together with Jan Lievens. At this time, Rembrandt mainly painted biblical scenes in a precise style and with vibrant colours.",
        descriptionMore: "In 1631, he moved to Amsterdam where he received numerous commissions for portraits. His many pupils included Ferdinand Bol, Govert Flinck and Carel Fabritius. In this period, Rembrandt develop a more powerful chiaroscuro, a looser brush and a greater sense of drama. He focused more on historical scenes, and made numerous etchings and drawings. In 1634, Rembrandt married Saskia Uylenburgh. They had a son, Titus, in 1641. Then a year later Saskia died. Later, in 1654, Rembrandt had a daughter with Hendrickje Stoffels. By now, he had accumulated huge debts and was forced to sell his house and property. He died in 1669 and was buried in Amsterdam's Westerkerk.",
        imageOne: "/images/The-Night-Watch-Rembrandt.jpg",
        imageOneName: "The Night Watch",
        imageTwo: "/images/Self-portrait-Rembrandt.jpg",
        imageTwoName: "Self portrait",
        imageThree: "/images/Liggende-leeuw-Rembrandt.jpg",
        imageThreeName: "Liggende leeuw"
    },
    {
        name: "Rembrandt van Rijn",
        descriptionLess: "Rembrandt van Rijn (1606-1669) was born in Leiden, the son of a miller. After finishing Latin School, his parents enrolled him at Leiden University. Rembrandt soon dropped out and became an apprentice painter under Jacob van Swanenburch in Leiden, and later Pieter Lastman in Amsterdam. Back in Leiden, he set up as an independent artist together with Jan Lievens. At this time, Rembrandt mainly painted biblical scenes in a precise style and with vibrant colours.",
        descriptionMore: "In 1631, he moved to Amsterdam where he received numerous commissions for portraits. His many pupils included Ferdinand Bol, Govert Flinck and Carel Fabritius. In this period, Rembrandt develop a more powerful chiaroscuro, a looser brush and a greater sense of drama. He focused more on historical scenes, and made numerous etchings and drawings. In 1634, Rembrandt married Saskia Uylenburgh. They had a son, Titus, in 1641. Then a year later Saskia died. Later, in 1654, Rembrandt had a daughter with Hendrickje Stoffels. By now, he had accumulated huge debts and was forced to sell his house and property. He died in 1669 and was buried in Amsterdam's Westerkerk.",
        imageOne: "/images/The-Night-Watch-Rembrandt.jpg",
        imageOneName: "The Night Watch",
        imageTwo: "/images/Self-portrait-Rembrandt.jpg",
        imageTwoName: "Self portrait",
        imageThree: "/images/Liggende-leeuw-Rembrandt.jpg",
        imageThreeName: "Liggende leeuw"
    },
    {
        name: "Rembrandt van Rijn",
        descriptionLess: "Rembrandt van Rijn (1606-1669) was born in Leiden, the son of a miller. After finishing Latin School, his parents enrolled him at Leiden University. Rembrandt soon dropped out and became an apprentice painter under Jacob van Swanenburch in Leiden, and later Pieter Lastman in Amsterdam. Back in Leiden, he set up as an independent artist together with Jan Lievens. At this time, Rembrandt mainly painted biblical scenes in a precise style and with vibrant colours.",
        descriptionMore: "In 1631, he moved to Amsterdam where he received numerous commissions for portraits. His many pupils included Ferdinand Bol, Govert Flinck and Carel Fabritius. In this period, Rembrandt develop a more powerful chiaroscuro, a looser brush and a greater sense of drama. He focused more on historical scenes, and made numerous etchings and drawings. In 1634, Rembrandt married Saskia Uylenburgh. They had a son, Titus, in 1641. Then a year later Saskia died. Later, in 1654, Rembrandt had a daughter with Hendrickje Stoffels. By now, he had accumulated huge debts and was forced to sell his house and property. He died in 1669 and was buried in Amsterdam's Westerkerk.",
        imageOne: "/images/The-Night-Watch-Rembrandt.jpg",
        imageOneName: "The Night Watch",
        imageTwo: "/images/Self-portrait-Rembrandt.jpg",
        imageTwoName: "Self portrait",
        imageThree: "/images/Liggende-leeuw-Rembrandt.jpg",
        imageThreeName: "Liggende leeuw"
    },
    {
        name: "Rembrandt van Rijn",
        descriptionLess: "Rembrandt van Rijn (1606-1669) was born in Leiden, the son of a miller. After finishing Latin School, his parents enrolled him at Leiden University. Rembrandt soon dropped out and became an apprentice painter under Jacob van Swanenburch in Leiden, and later Pieter Lastman in Amsterdam. Back in Leiden, he set up as an independent artist together with Jan Lievens. At this time, Rembrandt mainly painted biblical scenes in a precise style and with vibrant colours.",
        descriptionMore: "In 1631, he moved to Amsterdam where he received numerous commissions for portraits. His many pupils included Ferdinand Bol, Govert Flinck and Carel Fabritius. In this period, Rembrandt develop a more powerful chiaroscuro, a looser brush and a greater sense of drama. He focused more on historical scenes, and made numerous etchings and drawings. In 1634, Rembrandt married Saskia Uylenburgh. They had a son, Titus, in 1641. Then a year later Saskia died. Later, in 1654, Rembrandt had a daughter with Hendrickje Stoffels. By now, he had accumulated huge debts and was forced to sell his house and property. He died in 1669 and was buried in Amsterdam's Westerkerk.",
        imageOne: "/images/The-Night-Watch-Rembrandt.jpg",
        imageOneName: "The Night Watch",
        imageTwo: "/images/Self-portrait-Rembrandt.jpg",
        imageTwoName: "Self portrait",
        imageThree: "/images/Liggende-leeuw-Rembrandt.jpg",
        imageThreeName: "Liggende leeuw"
    },
    {
        name: "Rembrandt van Rijn",
        descriptionLess: "Rembrandt van Rijn (1606-1669) was born in Leiden, the son of a miller. After finishing Latin School, his parents enrolled him at Leiden University. Rembrandt soon dropped out and became an apprentice painter under Jacob van Swanenburch in Leiden, and later Pieter Lastman in Amsterdam. Back in Leiden, he set up as an independent artist together with Jan Lievens. At this time, Rembrandt mainly painted biblical scenes in a precise style and with vibrant colours.",
        descriptionMore: "In 1631, he moved to Amsterdam where he received numerous commissions for portraits. His many pupils included Ferdinand Bol, Govert Flinck and Carel Fabritius. In this period, Rembrandt develop a more powerful chiaroscuro, a looser brush and a greater sense of drama. He focused more on historical scenes, and made numerous etchings and drawings. In 1634, Rembrandt married Saskia Uylenburgh. They had a son, Titus, in 1641. Then a year later Saskia died. Later, in 1654, Rembrandt had a daughter with Hendrickje Stoffels. By now, he had accumulated huge debts and was forced to sell his house and property. He died in 1669 and was buried in Amsterdam's Westerkerk.",
        imageOne: "/images/The-Night-Watch-Rembrandt.jpg",
        imageOneName: "The Night Watch",
        imageTwo: "/images/Self-portrait-Rembrandt.jpg",
        imageTwoName: "Self portrait",
        imageThree: "/images/Liggende-leeuw-Rembrandt.jpg",
        imageThreeName: "Liggende leeuw"
    },
    {
        name: "Rembrandt van Rijn",
        descriptionLess: "Rembrandt van Rijn (1606-1669) was born in Leiden, the son of a miller. After finishing Latin School, his parents enrolled him at Leiden University. Rembrandt soon dropped out and became an apprentice painter under Jacob van Swanenburch in Leiden, and later Pieter Lastman in Amsterdam. Back in Leiden, he set up as an independent artist together with Jan Lievens. At this time, Rembrandt mainly painted biblical scenes in a precise style and with vibrant colours.",
        descriptionMore: "In 1631, he moved to Amsterdam where he received numerous commissions for portraits. His many pupils included Ferdinand Bol, Govert Flinck and Carel Fabritius. In this period, Rembrandt develop a more powerful chiaroscuro, a looser brush and a greater sense of drama. He focused more on historical scenes, and made numerous etchings and drawings. In 1634, Rembrandt married Saskia Uylenburgh. They had a son, Titus, in 1641. Then a year later Saskia died. Later, in 1654, Rembrandt had a daughter with Hendrickje Stoffels. By now, he had accumulated huge debts and was forced to sell his house and property. He died in 1669 and was buried in Amsterdam's Westerkerk.",
        imageOne: "/images/The-Night-Watch-Rembrandt.jpg",
        imageOneName: "The Night Watch",
        imageTwo: "/images/Self-portrait-Rembrandt.jpg",
        imageTwoName: "Self portrait",
        imageThree: "/images/Liggende-leeuw-Rembrandt.jpg",
        imageThreeName: "Liggende leeuw"
    },
    {
        name: "Rembrandt van Rijn",
        descriptionLess: "Rembrandt van Rijn (1606-1669) was born in Leiden, the son of a miller. After finishing Latin School, his parents enrolled him at Leiden University. Rembrandt soon dropped out and became an apprentice painter under Jacob van Swanenburch in Leiden, and later Pieter Lastman in Amsterdam. Back in Leiden, he set up as an independent artist together with Jan Lievens. At this time, Rembrandt mainly painted biblical scenes in a precise style and with vibrant colours.",
        descriptionMore: "In 1631, he moved to Amsterdam where he received numerous commissions for portraits. His many pupils included Ferdinand Bol, Govert Flinck and Carel Fabritius. In this period, Rembrandt develop a more powerful chiaroscuro, a looser brush and a greater sense of drama. He focused more on historical scenes, and made numerous etchings and drawings. In 1634, Rembrandt married Saskia Uylenburgh. They had a son, Titus, in 1641. Then a year later Saskia died. Later, in 1654, Rembrandt had a daughter with Hendrickje Stoffels. By now, he had accumulated huge debts and was forced to sell his house and property. He died in 1669 and was buried in Amsterdam's Westerkerk.",
        imageOne: "/images/The-Night-Watch-Rembrandt.jpg",
        imageOneName: "The Night Watch",
        imageTwo: "/images/Self-portrait-Rembrandt.jpg",
        imageTwoName: "Self portrait",
        imageThree: "/images/Liggende-leeuw-Rembrandt.jpg",
        imageThreeName: "Liggende leeuw"
    },
    {
        name: "Rembrandt van Rijn",
        descriptionLess: "Rembrandt van Rijn (1606-1669) was born in Leiden, the son of a miller. After finishing Latin School, his parents enrolled him at Leiden University. Rembrandt soon dropped out and became an apprentice painter under Jacob van Swanenburch in Leiden, and later Pieter Lastman in Amsterdam. Back in Leiden, he set up as an independent artist together with Jan Lievens. At this time, Rembrandt mainly painted biblical scenes in a precise style and with vibrant colours.",
        descriptionMore: "In 1631, he moved to Amsterdam where he received numerous commissions for portraits. His many pupils included Ferdinand Bol, Govert Flinck and Carel Fabritius. In this period, Rembrandt develop a more powerful chiaroscuro, a looser brush and a greater sense of drama. He focused more on historical scenes, and made numerous etchings and drawings. In 1634, Rembrandt married Saskia Uylenburgh. They had a son, Titus, in 1641. Then a year later Saskia died. Later, in 1654, Rembrandt had a daughter with Hendrickje Stoffels. By now, he had accumulated huge debts and was forced to sell his house and property. He died in 1669 and was buried in Amsterdam's Westerkerk.",
        imageOne: "/images/The-Night-Watch-Rembrandt.jpg",
        imageOneName: "The Night Watch",
        imageTwo: "/images/Self-portrait-Rembrandt.jpg",
        imageTwoName: "Self portrait",
        imageThree: "/images/Liggende-leeuw-Rembrandt.jpg",
        imageThreeName: "Liggende leeuw"
    },
    {
        name: "Rembrandt van Rijn",
        descriptionLess: "Rembrandt van Rijn (1606-1669) was born in Leiden, the son of a miller. After finishing Latin School, his parents enrolled him at Leiden University. Rembrandt soon dropped out and became an apprentice painter under Jacob van Swanenburch in Leiden, and later Pieter Lastman in Amsterdam. Back in Leiden, he set up as an independent artist together with Jan Lievens. At this time, Rembrandt mainly painted biblical scenes in a precise style and with vibrant colours.",
        descriptionMore: "In 1631, he moved to Amsterdam where he received numerous commissions for portraits. His many pupils included Ferdinand Bol, Govert Flinck and Carel Fabritius. In this period, Rembrandt develop a more powerful chiaroscuro, a looser brush and a greater sense of drama. He focused more on historical scenes, and made numerous etchings and drawings. In 1634, Rembrandt married Saskia Uylenburgh. They had a son, Titus, in 1641. Then a year later Saskia died. Later, in 1654, Rembrandt had a daughter with Hendrickje Stoffels. By now, he had accumulated huge debts and was forced to sell his house and property. He died in 1669 and was buried in Amsterdam's Westerkerk.",
        imageOne: "/images/The-Night-Watch-Rembrandt.jpg",
        imageOneName: "The Night Watch",
        imageTwo: "/images/Self-portrait-Rembrandt.jpg",
        imageTwoName: "Self portrait",
        imageThree: "/images/Liggende-leeuw-Rembrandt.jpg",
        imageThreeName: "Liggende leeuw"
    },
    {
        name: "Rembrandt van Rijn",
        descriptionLess: "Rembrandt van Rijn (1606-1669) was born in Leiden, the son of a miller. After finishing Latin School, his parents enrolled him at Leiden University. Rembrandt soon dropped out and became an apprentice painter under Jacob van Swanenburch in Leiden, and later Pieter Lastman in Amsterdam. Back in Leiden, he set up as an independent artist together with Jan Lievens. At this time, Rembrandt mainly painted biblical scenes in a precise style and with vibrant colours.",
        descriptionMore: "In 1631, he moved to Amsterdam where he received numerous commissions for portraits. His many pupils included Ferdinand Bol, Govert Flinck and Carel Fabritius. In this period, Rembrandt develop a more powerful chiaroscuro, a looser brush and a greater sense of drama. He focused more on historical scenes, and made numerous etchings and drawings. In 1634, Rembrandt married Saskia Uylenburgh. They had a son, Titus, in 1641. Then a year later Saskia died. Later, in 1654, Rembrandt had a daughter with Hendrickje Stoffels. By now, he had accumulated huge debts and was forced to sell his house and property. He died in 1669 and was buried in Amsterdam's Westerkerk.",
        imageOne: "/images/The-Night-Watch-Rembrandt.jpg",
        imageOneName: "The Night Watch",
        imageTwo: "/images/Self-portrait-Rembrandt.jpg",
        imageTwoName: "Self portrait",
        imageThree: "/images/Liggende-leeuw-Rembrandt.jpg",
        imageThreeName: "Liggende leeuw"
    },
    {
        name: "Rembrandt van Rijn",
        descriptionLess: "Rembrandt van Rijn (1606-1669) was born in Leiden, the son of a miller. After finishing Latin School, his parents enrolled him at Leiden University. Rembrandt soon dropped out and became an apprentice painter under Jacob van Swanenburch in Leiden, and later Pieter Lastman in Amsterdam. Back in Leiden, he set up as an independent artist together with Jan Lievens. At this time, Rembrandt mainly painted biblical scenes in a precise style and with vibrant colours.",
        descriptionMore: "In 1631, he moved to Amsterdam where he received numerous commissions for portraits. His many pupils included Ferdinand Bol, Govert Flinck and Carel Fabritius. In this period, Rembrandt develop a more powerful chiaroscuro, a looser brush and a greater sense of drama. He focused more on historical scenes, and made numerous etchings and drawings. In 1634, Rembrandt married Saskia Uylenburgh. They had a son, Titus, in 1641. Then a year later Saskia died. Later, in 1654, Rembrandt had a daughter with Hendrickje Stoffels. By now, he had accumulated huge debts and was forced to sell his house and property. He died in 1669 and was buried in Amsterdam's Westerkerk.",
        imageOne: "/images/The-Night-Watch-Rembrandt.jpg",
        imageOneName: "The Night Watch",
        imageTwo: "/images/Self-portrait-Rembrandt.jpg",
        imageTwoName: "Self portrait",
        imageThree: "/images/Liggende-leeuw-Rembrandt.jpg",
        imageThreeName: "Liggende leeuw"
    },
    {
        name: "Rembrandt van Rijn",
        descriptionLess: "Rembrandt van Rijn (1606-1669) was born in Leiden, the son of a miller. After finishing Latin School, his parents enrolled him at Leiden University. Rembrandt soon dropped out and became an apprentice painter under Jacob van Swanenburch in Leiden, and later Pieter Lastman in Amsterdam. Back in Leiden, he set up as an independent artist together with Jan Lievens. At this time, Rembrandt mainly painted biblical scenes in a precise style and with vibrant colours.",
        descriptionMore: "In 1631, he moved to Amsterdam where he received numerous commissions for portraits. His many pupils included Ferdinand Bol, Govert Flinck and Carel Fabritius. In this period, Rembrandt develop a more powerful chiaroscuro, a looser brush and a greater sense of drama. He focused more on historical scenes, and made numerous etchings and drawings. In 1634, Rembrandt married Saskia Uylenburgh. They had a son, Titus, in 1641. Then a year later Saskia died. Later, in 1654, Rembrandt had a daughter with Hendrickje Stoffels. By now, he had accumulated huge debts and was forced to sell his house and property. He died in 1669 and was buried in Amsterdam's Westerkerk.",
        imageOne: "/images/The-Night-Watch-Rembrandt.jpg",
        imageOneName: "The Night Watch",
        imageTwo: "/images/Self-portrait-Rembrandt.jpg",
        imageTwoName: "Self portrait",
        imageThree: "/images/Liggende-leeuw-Rembrandt.jpg",
        imageThreeName: "Liggende leeuw"
    },
    {
        name: "Rembrandt van Rijn",
        descriptionLess: "Rembrandt van Rijn (1606-1669) was born in Leiden, the son of a miller. After finishing Latin School, his parents enrolled him at Leiden University. Rembrandt soon dropped out and became an apprentice painter under Jacob van Swanenburch in Leiden, and later Pieter Lastman in Amsterdam. Back in Leiden, he set up as an independent artist together with Jan Lievens. At this time, Rembrandt mainly painted biblical scenes in a precise style and with vibrant colours.",
        descriptionMore: "In 1631, he moved to Amsterdam where he received numerous commissions for portraits. His many pupils included Ferdinand Bol, Govert Flinck and Carel Fabritius. In this period, Rembrandt develop a more powerful chiaroscuro, a looser brush and a greater sense of drama. He focused more on historical scenes, and made numerous etchings and drawings. In 1634, Rembrandt married Saskia Uylenburgh. They had a son, Titus, in 1641. Then a year later Saskia died. Later, in 1654, Rembrandt had a daughter with Hendrickje Stoffels. By now, he had accumulated huge debts and was forced to sell his house and property. He died in 1669 and was buried in Amsterdam's Westerkerk.",
        imageOne: "/images/The-Night-Watch-Rembrandt.jpg",
        imageOneName: "The Night Watch",
        imageTwo: "/images/Self-portrait-Rembrandt.jpg",
        imageTwoName: "Self portrait",
        imageThree: "/images/Liggende-leeuw-Rembrandt.jpg",
        imageThreeName: "Liggende leeuw"
    },
    {
        name: "Rembrandt van Rijn",
        descriptionLess: "Rembrandt van Rijn (1606-1669) was born in Leiden, the son of a miller. After finishing Latin School, his parents enrolled him at Leiden University. Rembrandt soon dropped out and became an apprentice painter under Jacob van Swanenburch in Leiden, and later Pieter Lastman in Amsterdam. Back in Leiden, he set up as an independent artist together with Jan Lievens. At this time, Rembrandt mainly painted biblical scenes in a precise style and with vibrant colours.",
        descriptionMore: "In 1631, he moved to Amsterdam where he received numerous commissions for portraits. His many pupils included Ferdinand Bol, Govert Flinck and Carel Fabritius. In this period, Rembrandt develop a more powerful chiaroscuro, a looser brush and a greater sense of drama. He focused more on historical scenes, and made numerous etchings and drawings. In 1634, Rembrandt married Saskia Uylenburgh. They had a son, Titus, in 1641. Then a year later Saskia died. Later, in 1654, Rembrandt had a daughter with Hendrickje Stoffels. By now, he had accumulated huge debts and was forced to sell his house and property. He died in 1669 and was buried in Amsterdam's Westerkerk.",
        imageOne: "/images/The-Night-Watch-Rembrandt.jpg",
        imageOneName: "The Night Watch",
        imageTwo: "/images/Self-portrait-Rembrandt.jpg",
        imageTwoName: "Self portrait",
        imageThree: "/images/Liggende-leeuw-Rembrandt.jpg",
        imageThreeName: "Liggende leeuw"
    },
    {
        name: "Rembrandt van Rijn",
        descriptionLess: "Rembrandt van Rijn (1606-1669) was born in Leiden, the son of a miller. After finishing Latin School, his parents enrolled him at Leiden University. Rembrandt soon dropped out and became an apprentice painter under Jacob van Swanenburch in Leiden, and later Pieter Lastman in Amsterdam. Back in Leiden, he set up as an independent artist together with Jan Lievens. At this time, Rembrandt mainly painted biblical scenes in a precise style and with vibrant colours.",
        descriptionMore: "In 1631, he moved to Amsterdam where he received numerous commissions for portraits. His many pupils included Ferdinand Bol, Govert Flinck and Carel Fabritius. In this period, Rembrandt develop a more powerful chiaroscuro, a looser brush and a greater sense of drama. He focused more on historical scenes, and made numerous etchings and drawings. In 1634, Rembrandt married Saskia Uylenburgh. They had a son, Titus, in 1641. Then a year later Saskia died. Later, in 1654, Rembrandt had a daughter with Hendrickje Stoffels. By now, he had accumulated huge debts and was forced to sell his house and property. He died in 1669 and was buried in Amsterdam's Westerkerk.",
        imageOne: "/images/The-Night-Watch-Rembrandt.jpg",
        imageOneName: "The Night Watch",
        imageTwo: "/images/Self-portrait-Rembrandt.jpg",
        imageTwoName: "Self portrait",
        imageThree: "/images/Liggende-leeuw-Rembrandt.jpg",
        imageThreeName: "Liggende leeuw"
    },
    {
        name: "Rembrandt van Rijn",
        descriptionLess: "Rembrandt van Rijn (1606-1669) was born in Leiden, the son of a miller. After finishing Latin School, his parents enrolled him at Leiden University. Rembrandt soon dropped out and became an apprentice painter under Jacob van Swanenburch in Leiden, and later Pieter Lastman in Amsterdam. Back in Leiden, he set up as an independent artist together with Jan Lievens. At this time, Rembrandt mainly painted biblical scenes in a precise style and with vibrant colours.",
        descriptionMore: "In 1631, he moved to Amsterdam where he received numerous commissions for portraits. His many pupils included Ferdinand Bol, Govert Flinck and Carel Fabritius. In this period, Rembrandt develop a more powerful chiaroscuro, a looser brush and a greater sense of drama. He focused more on historical scenes, and made numerous etchings and drawings. In 1634, Rembrandt married Saskia Uylenburgh. They had a son, Titus, in 1641. Then a year later Saskia died. Later, in 1654, Rembrandt had a daughter with Hendrickje Stoffels. By now, he had accumulated huge debts and was forced to sell his house and property. He died in 1669 and was buried in Amsterdam's Westerkerk.",
        imageOne: "/images/The-Night-Watch-Rembrandt.jpg",
        imageOneName: "The Night Watch",
        imageTwo: "/images/Self-portrait-Rembrandt.jpg",
        imageTwoName: "Self portrait",
        imageThree: "/images/Liggende-leeuw-Rembrandt.jpg",
        imageThreeName: "Liggende leeuw"
    },
    {
        name: "Rembrandt van Rijn",
        descriptionLess: "Rembrandt van Rijn (1606-1669) was born in Leiden, the son of a miller. After finishing Latin School, his parents enrolled him at Leiden University. Rembrandt soon dropped out and became an apprentice painter under Jacob van Swanenburch in Leiden, and later Pieter Lastman in Amsterdam. Back in Leiden, he set up as an independent artist together with Jan Lievens. At this time, Rembrandt mainly painted biblical scenes in a precise style and with vibrant colours.",
        descriptionMore: "In 1631, he moved to Amsterdam where he received numerous commissions for portraits. His many pupils included Ferdinand Bol, Govert Flinck and Carel Fabritius. In this period, Rembrandt develop a more powerful chiaroscuro, a looser brush and a greater sense of drama. He focused more on historical scenes, and made numerous etchings and drawings. In 1634, Rembrandt married Saskia Uylenburgh. They had a son, Titus, in 1641. Then a year later Saskia died. Later, in 1654, Rembrandt had a daughter with Hendrickje Stoffels. By now, he had accumulated huge debts and was forced to sell his house and property. He died in 1669 and was buried in Amsterdam's Westerkerk.",
        imageOne: "/images/The-Night-Watch-Rembrandt.jpg",
        imageOneName: "The Night Watch",
        imageTwo: "/images/Self-portrait-Rembrandt.jpg",
        imageTwoName: "Self portrait",
        imageThree: "/images/Liggende-leeuw-Rembrandt.jpg",
        imageThreeName: "Liggende leeuw"
    },
    {
        name: "Rembrandt van Rijn",
        descriptionLess: "Rembrandt van Rijn (1606-1669) was born in Leiden, the son of a miller. After finishing Latin School, his parents enrolled him at Leiden University. Rembrandt soon dropped out and became an apprentice painter under Jacob van Swanenburch in Leiden, and later Pieter Lastman in Amsterdam. Back in Leiden, he set up as an independent artist together with Jan Lievens. At this time, Rembrandt mainly painted biblical scenes in a precise style and with vibrant colours.",
        descriptionMore: "In 1631, he moved to Amsterdam where he received numerous commissions for portraits. His many pupils included Ferdinand Bol, Govert Flinck and Carel Fabritius. In this period, Rembrandt develop a more powerful chiaroscuro, a looser brush and a greater sense of drama. He focused more on historical scenes, and made numerous etchings and drawings. In 1634, Rembrandt married Saskia Uylenburgh. They had a son, Titus, in 1641. Then a year later Saskia died. Later, in 1654, Rembrandt had a daughter with Hendrickje Stoffels. By now, he had accumulated huge debts and was forced to sell his house and property. He died in 1669 and was buried in Amsterdam's Westerkerk.",
        imageOne: "/images/The-Night-Watch-Rembrandt.jpg",
        imageOneName: "The Night Watch",
        imageTwo: "/images/Self-portrait-Rembrandt.jpg",
        imageTwoName: "Self portrait",
        imageThree: "/images/Liggende-leeuw-Rembrandt.jpg",
        imageThreeName: "Liggende leeuw"
    },
    {
        name: "Rembrandt van Rijn",
        descriptionLess: "Rembrandt van Rijn (1606-1669) was born in Leiden, the son of a miller. After finishing Latin School, his parents enrolled him at Leiden University. Rembrandt soon dropped out and became an apprentice painter under Jacob van Swanenburch in Leiden, and later Pieter Lastman in Amsterdam. Back in Leiden, he set up as an independent artist together with Jan Lievens. At this time, Rembrandt mainly painted biblical scenes in a precise style and with vibrant colours.",
        descriptionMore: "In 1631, he moved to Amsterdam where he received numerous commissions for portraits. His many pupils included Ferdinand Bol, Govert Flinck and Carel Fabritius. In this period, Rembrandt develop a more powerful chiaroscuro, a looser brush and a greater sense of drama. He focused more on historical scenes, and made numerous etchings and drawings. In 1634, Rembrandt married Saskia Uylenburgh. They had a son, Titus, in 1641. Then a year later Saskia died. Later, in 1654, Rembrandt had a daughter with Hendrickje Stoffels. By now, he had accumulated huge debts and was forced to sell his house and property. He died in 1669 and was buried in Amsterdam's Westerkerk.",
        imageOne: "/images/The-Night-Watch-Rembrandt.jpg",
        imageOneName: "The Night Watch",
        imageTwo: "/images/Self-portrait-Rembrandt.jpg",
        imageTwoName: "Self portrait",
        imageThree: "/images/Liggende-leeuw-Rembrandt.jpg",
        imageThreeName: "Liggende leeuw"
    },
    {
        name: "Rembrandt van Rijn",
        descriptionLess: "Rembrandt van Rijn (1606-1669) was born in Leiden, the son of a miller. After finishing Latin School, his parents enrolled him at Leiden University. Rembrandt soon dropped out and became an apprentice painter under Jacob van Swanenburch in Leiden, and later Pieter Lastman in Amsterdam. Back in Leiden, he set up as an independent artist together with Jan Lievens. At this time, Rembrandt mainly painted biblical scenes in a precise style and with vibrant colours.",
        descriptionMore: "In 1631, he moved to Amsterdam where he received numerous commissions for portraits. His many pupils included Ferdinand Bol, Govert Flinck and Carel Fabritius. In this period, Rembrandt develop a more powerful chiaroscuro, a looser brush and a greater sense of drama. He focused more on historical scenes, and made numerous etchings and drawings. In 1634, Rembrandt married Saskia Uylenburgh. They had a son, Titus, in 1641. Then a year later Saskia died. Later, in 1654, Rembrandt had a daughter with Hendrickje Stoffels. By now, he had accumulated huge debts and was forced to sell his house and property. He died in 1669 and was buried in Amsterdam's Westerkerk.",
        imageOne: "/images/The-Night-Watch-Rembrandt.jpg",
        imageOneName: "The Night Watch",
        imageTwo: "/images/Self-portrait-Rembrandt.jpg",
        imageTwoName: "Self portrait",
        imageThree: "/images/Liggende-leeuw-Rembrandt.jpg",
        imageThreeName: "Liggende leeuw"
    },
    {
        name: "Rembrandt van Rijn",
        descriptionLess: "Rembrandt van Rijn (1606-1669) was born in Leiden, the son of a miller. After finishing Latin School, his parents enrolled him at Leiden University. Rembrandt soon dropped out and became an apprentice painter under Jacob van Swanenburch in Leiden, and later Pieter Lastman in Amsterdam. Back in Leiden, he set up as an independent artist together with Jan Lievens. At this time, Rembrandt mainly painted biblical scenes in a precise style and with vibrant colours.",
        descriptionMore: "In 1631, he moved to Amsterdam where he received numerous commissions for portraits. His many pupils included Ferdinand Bol, Govert Flinck and Carel Fabritius. In this period, Rembrandt develop a more powerful chiaroscuro, a looser brush and a greater sense of drama. He focused more on historical scenes, and made numerous etchings and drawings. In 1634, Rembrandt married Saskia Uylenburgh. They had a son, Titus, in 1641. Then a year later Saskia died. Later, in 1654, Rembrandt had a daughter with Hendrickje Stoffels. By now, he had accumulated huge debts and was forced to sell his house and property. He died in 1669 and was buried in Amsterdam's Westerkerk.",
        imageOne: "/images/The-Night-Watch-Rembrandt.jpg",
        imageOneName: "The Night Watch",
        imageTwo: "/images/Self-portrait-Rembrandt.jpg",
        imageTwoName: "Self portrait",
        imageThree: "/images/Liggende-leeuw-Rembrandt.jpg",
        imageThreeName: "Liggende leeuw"
    }
]


