const myArtistsAndImages = [
    {
        id: "01",
        name: "Rembrandt van Rijn",
        descriptionLess: "Rembrandt van Rijn (1606-1669) was born in Leiden, the son of a miller. After finishing Latin School, his parents enrolled him at Leiden University. Rembrandt soon dropped out and became an apprentice painter under Jacob van Swanenburch in Leiden, and later Pieter Lastman in Amsterdam.",
        descriptionMore: "Back in Leiden, he set up as an independent artist together with Jan Lievens. At this time, Rembrandt mainly painted biblical scenes in a precise style and with vibrant colours. In 1631, he moved to Amsterdam where he received numerous commissions for portraits. His many pupils included Ferdinand Bol, Govert Flinck and Carel Fabritius. In this period, Rembrandt develop a more powerful chiaroscuro, a looser brush and a greater sense of drama. He focused more on historical scenes, and made numerous etchings and drawings. In 1634, Rembrandt married Saskia Uylenburgh. They had a son, Titus, in 1641. Then a year later Saskia died. Later, in 1654, Rembrandt had a daughter with Hendrickje Stoffels. By now, he had accumulated huge debts and was forced to sell his house and property. He died in 1669 and was buried in Amsterdam's Westerkerk.",
        image1: "/images/The-Night-Watch-Rembrandt.jpg",
        image1Name: "The Night Watch",
        image2: "/images/Self-portrait-Rembrandt.jpg",
        image2Name: "Self portrait",
        image3: "/images/Liggende-leeuw-Rembrandt.jpg",
        image3Name: "Reclining Lion"
    },
    {
        id: "02",
        name: "Johannes Vermeer",
        descriptionLess: "Today Johannes Vermeer (1632-1675) is one of the most celebrated Dutch 17th century masters. Yet for centuries little importance was attached to his name. Works now known as Vermeers were attributed to other artists. It was only in the 1870s that he was rediscovered and 35 paintings identified as his.",
        descriptionMore: "The son of a silk worker who bought and sold art, Vermeer lived and worked in Delft all his life. He may have served his apprenticeship under fellow townsman Carel Fabritius. In 1653, he joined the local artists guild, which he led at various times. Vermeer’s early paintings of historical scenes reveal the influence of the Utrecht Caravaggists. His later paintings are meticulous compositions of interiors featuring one or two figures, usually women. These are intimate genre paintings in which the subject is engaged in some everyday activity, usually in the light of a nearby window. Vermeer could render the way light plays on objects like few others. The Rijksmuseum has three domestic interiors by Vermeer and one outdoor scene: his world-famous Little Street.",
        image1: "/images/The-Milkmaid-Vermeer.jpg",
        image1Name: "The Milkmaid",
        image2: "/images/Woman-Reading-a-Letter-Vermeer.jpg",
        image2Name: "Woman Reading a Letter",
        image3: "/images/View-of-Houses-in-Delft-Vermeer.jpg",
        image3Name: "View of Houses in Delft, Known as The Little Street"
    },
    {
        id: "03",
        name: "Jan Havicksz. Steen",
        descriptionLess: "Jan Havicksz Steen (ca. 1625-1679) was born in Leiden, the son of a brewer. Educated at a Latin school, in 1646 he enrolled at Leiden university yet never graduated. Instead, he took an apprenticeship as a painter, although little is known about this.",
        descriptionMore: "Eighteenth-century biographers record that his teachers included Nicolaus Knupfer, Adriaen van Ostade and landscapist Jan van Goyen. In 1648, already a master, he helped set up a guild of artists in Leiden, in which he served in various capacities. Steen painted a huge number of works, especially genre paintings showing cheerful people having fun. He also painted portraits, as well as historical scenes. To augment his income, Steen started a brewery in Delft and opened a tavern at his house. Biographers have described him as a man with little sense of restraint, yet that seems to be based more on his paintings than on hard fact. Jan Steen is buried in St Pieter's church in Leiden.",
        image1: "/images/The-Merry-Family-Steen.jpg",
        image1Name: "The Merry Family",
        image2: "/images/The-Feast-of-St-Nicholas-Steen.jpg",
        image2Name: "The Feast of St Nicholas",
        image3: "/images/Woman-at-her-Toilet-Steen.jpg",
        image3Name: "Woman at her Toilet"
    },
    {
        id: "04",
        name: "Hendrick Avercamp",
        descriptionLess: "Born in Amsterdam, Hendrick Avercamp (1585-1634) grew up in Kampen. He lived and worked there from 1614 until his death in 1634. Avercamp is mentioned in various documents as the Kampen Mute, so it is assumed that he was deaf and dumb.",
        descriptionMore: "Avercamp had originally been taught in Amsterdam by Pieter Isacksz, and specialised in winter landscapes. He adopted the Flemish tradition, which was continued in Amsterdam by Gilles van Coninxloo and Pieter Vinckboons. Avercamp's early landscapes have a clear narrative in style, often containing risqué anecdotes. Later, his work acquired a more atmospheric quality.",
        image1: "/images/Fishermen-by-Moonlight-Avercamp.jpg",
        image1Name: "Fishermen by Moonlight",
        image2: "/images/Ice-skating-in-a-Village-Avercamp.jpg",
        image2Name: "Ice-skating in a Village",
        image3: "/images/Winter-scene-Avercamp.jpg",
        image3Name: "Winter scene; a woman and a boy on a small bridge"
    },
    {
        id: "05",
        name: "Hendrick Goltzius",
        descriptionLess: "Draughtsman, engraver and painter Hendrick Goltzius (1558-1617) was born in Mülbracht (now Bracht-am-Niederrhein) in Germany. In 1577, he followed his teacher, printer Dirck Volkertsz Coornhert, to Haarlem.",
        descriptionMore: "Along with Karel van Mander and Cornelis Cornelisz van Haarlem, Goltzius was part of the Haarlem circle that introduced Mannerist art to the Netherlands. Their style is characterised by complex compositions and figures with exaggerated physiques and comparatively small heads. Following a visit to Italy in the 1590s, Goltzius developed a more neoclassical style, with his figures and buildings tending towards classical forms. Goltzius's oeuvre offers an interesting reflection of the changes taking place in Dutch art around 1600. In his day, Goltzius enjoyed an international reputation for the technical brilliance of his engravings.",
        image1: "/images/Lot-and-his-Daughters-Goltzius.jpg",
        image1Name: "Lot and his Daughters",
        image2: "/images/A-Seated-Monkey-on-a-Chain-Goltzius.jpg",
        image2Name: "A Seated Monkey on a Chain",
        image3: "/images/Neptunus-en-Amphitrite-Goltzius.jpg",
        image3Name: "Neptunus en Amphitrite"
    },
    {
        id: "06",
        name: "Jacob Isaacksz. van Ruisdael",
        descriptionLess: "The Haarlem-born painter Jacob van Ruisdael (ca. 1628-1682) began to paint at an early age. His first work dates from 1646. Ruisdael probably had lessons from his father, but his uncle, the artist Salomon van Ruysdael, must also have been a great influence on the young painter.",
        descriptionMore: "As well as being a painter, Ruisdael was also a doctor. He painted not only woodland landscapes with strong, central motifs such as ruins, watermills and oaks, but also cityscapes and seascapes. Ruisdael's compositions are often more imposing than reality. His 'Bentheim Castle' and 'Windmill at Wijk bij Duurstede' are good examples of this. Ruisdael travelled in order to get inspiration for his paintings. On these trips he made many drawings. There are also some etchings which he is known to have made. In the 1650s, probably around 1656, Jacob van Ruisdael moved to Amsterdam, where he lived and worked until his death in 1682.",
        image1: "/images/Bentheim-Castle-Ruisdael.jpg",
        image1Name: "Bentheim Castle",
        image2: "/images/Landscape-with-Waterfall-Ruisdael.jpg",
        image2Name: "Landscape with Waterfall",
        image3: "/images/The-Windmill-at-Wijk-bij-Duurstede-Ruisdael.jpg",
        image3Name: "The Windmill at Wijk bij Duurstede"
    },
    {
        id: "07",
        name: "George Hendrik Breitner",
        descriptionLess: "George Hendrik Breitner (1857-1923) was born in Rotterdam. In 1876, he enrolled at the academy in The Hague. Later, he worked at Willem Maris's studio. In this early period he was especially influenced by the painters of the Hague School. Breitner preferred working-class models: labourers, servant girls and people from lower-class neighbourhoods.",
        descriptionMore: "He saw himself as 'le peintre du peuple', the people's painter. In 1886, he moved to Amsterdam, where he recorded the life of the city in sketches, paintings and photos. Sometimes he made several pictures of the same subject, from different angles or in different weather conditions. Photos might serve as an example for a painting, as for his portraits of girls in kimonos, or as general reference material. Breitner often collaborated with Isaac Israels; both painters are referred to as Amsterdam Impressionists. Conservative critics called Breitner's style 'unfinished'.",
        image1: "/images/Girl-in-a-White-Kimono-Breitner.jpg",
        image1Name: "Girl in a White Kimono",
        image2: "/images/The-Rokin-in-Amsterdam-Breitner.jpg",
        image2Name: "The Rokin in Amsterdam",
        image3: "/images/The-Yellow-Riders-Breitner.jpg",
        image3Name: "The Yellow Riders"
    },
    {
        id: "08",
        name: "Caesar Boëtius van Everdingen",
        descriptionLess: "Caesar Boëtius van Everdingen (1616-1678) was born in Alkmaar. He joined Alkmaar’s St Luke's Guild at a remarkably young age in 1632. From 1641 to 1643 he was living in Amersfoort where he worked under the painter and architect Jacob van Campen.",
        descriptionMore: "In 1648, Van Everdingen moved to Haarlem. He was commissioned by Van Campen to complete two paintings for the Orange hall of the stadholder palace of Huis ten Bosch. In the 1650s, Van Everdingen specialised increasingly in history paintings which he painted in the classical style. In addition to these elevated historical scenes, Van Everdingen also painted genre pieces. By then an affluent man, Van Everdingen returned to Alkmaar in 1657, where he died in 1671. Van Everdingen's younger brother, Allart, was also a painter, mainly known for his landscapes.",
        image1: "/images/Girl-in-a-Large-Hat-Everdingen.jpg",
        image1Name: "Girl in a Large Hat",
        image2: "/images/Pan-and-Syrinx-Everdingen.jpg",
        image2Name: "Pan and Syrinx",
        image3: "/images/Willem-Jacobsz-Baert-Everdingen.jpg",
        image3Name: "Willem Jacobsz Baert (1636-84), Burgomaster of Alkmaar and Amsterdam"
    },
    {
        id: "09",
        name: "Lawrence Alma Tadema",
        descriptionLess: "Laurens Alma Tadema (1836-1912) was the son of a public notary in the village of Dronrijp in Friesland. At sixteen he enrolled at the art academy in Antwerp. It was on a trip to Pompeii in 1863, that Alma Tadema developed his love of Classical art and architecture which agreed in both style and content with his own precise, academic manner of painting.",
        descriptionMore: "In 1870, he moved to London, which was to remain his home, becoming a denizen (permanent resident) and changing his name to Lawrence. He was a popular artist and highly successful, receiving a knighthood in 1899. In addition to his depictions of life in Antiquity, he also painted portraits and theatre decors. In 1902, Alma Tadema visited Egypt, which gave his work a new impulse. Alma Tadema’s historical accuracy was remarkable for his time. It is not surprising that his paintings were considered reliable examples for historical films.",
        image1: "/images/Liggende-vrouw-met-tamboerijn-Tadema.jpg",
        image1Name: "Liggende vrouw met tamboerijn",
        image2: "/images/The-Death-of-the-Pharaohs-Firstborn-Son-Tadema.jpg",
        image2Name: "The Death of the Pharaoh’s Firstborn Son",
        image3: "/images/Mary-Magdalene-Tadema.jpg",
        image3Name: "Mary Magdalene"
    },
    {
        id: "10",
        name: "Ludolf Bakhuysen",
        descriptionLess: "Born in Emden in Germany, marine painter and printmaker Ludolf Bakhuysen (1630-1708) came to Amsterdam in 1649. There he was taught by landscape artist Allart van Everdingen and marine painter Hendrick Dubbels. His work also reveals the influence of Willem van de Velde I, another nautical specialist.",
        descriptionMore: "In addition to his views of harbours and portraits of ships, Bakhuysen painted many dramatic scenes of stormy seas and shipwrecks. It was said that he often went to sea when the weather turned bad, to see the effect at first hand. He depicted many episodes from Dutch maritime history. When the Van de Veldes moved to England around 1672, Bakhuysen remained the last great artist working in the genre in Holland.",
        image1: "/images/Rough-Sea-with-Ships-Bakhuysen.jpg",
        image1Name: "Rough Sea with Ships",
        image2: "/images/Warships-in-a-Heavy-Storm-Bakhuysen.jpg",
        image2Name: "Warships in a Heavy Storm",
        image3: "/images/The-Y-at-Amsterdam-Bakhuysen.jpg",
        image3Name: "The Y at Amsterdam, seen from the Mosselsteiger (mussel pier)"
    },
    {
        id: "11",
        name: "Gerrit Adriaensz. Berckheyde",
        descriptionLess: "Gerrit Berckheyde (1638-1698) was baptised on 6 June 1638 in Haarlem. He was apprenticed to his elder brother, Job Berckheyde and to Frans Hals. He and his brother worked in Heidelberg for a while for the Elector Palatine. ",
        descriptionMore: "In around 1660, he returned to Haarlem and in the summer of that year was admitted to the local St Luke’s guild of artists. In 1698, he drowned in Haarlem's Brouwersvaart canal. After 1660, Berckheyde painted almost only townscapes, mainly of Haarlem, Amsterdam and The Hague. Despite the number of works, and his frequent repetitions, he paintings are invariably of exceptional quality.",
        image1: "/images/The-Town-Hall-on-the-Dam-Berckheyde.jpg",
        image1Name: "The Town Hall on the Dam, Amsterdam",
        image2: "/images/Gezicht-op-de-Gouden-Bocht-Berckheyde.jpg",
        image2Name: "Gezicht op de Gouden Bocht in de Herengracht vanuit het oosten",
        image3: "/images/The-Main-Gate-to-Egmond-Castle-Berckheyde.jpg",
        image3Name: "The Main Gate to Egmond Castle"
    },
    {
        id: "12",
        name: "Cornelis Cornelisz. van Haarlem",
        descriptionLess: "Cornelis Cornelisz. van Haarlem (1562-1638) was born into an affluent family. When his parents fled the Spanish siege of Haarlem in 1572, Cornelis remained behind with Pieter Pietersz, to whom he was apprenticed. ",
        descriptionMore: "In 1580 and 1581, he studied under artists in Rouen and Antwerp, before returning to Haarlem. Around 1584, Cornelis met Hendrick Goltzius and Karel van Mander, forming their own Haarlem Academy. These three artists represent the Dutch brand of Mannerism, with complex compositions featuring nudes in twisted poses and intricate positions. Besides religious and mythological scenes, Cornelis van Haarlem also painted portraits, kitchen scenes and still lifes.",
        image1: "/images/Bathsheba-at-her-Toilet-Haarlem.jpg",
        image1Name: "Bathsheba at her Toilet",
        image2: "/images/The-Fall-of-Man-Haarlem.jpg",
        image2Name: "The Fall of Man",
        image3: "/images/The-Massacre-Haarlem.jpg",
        image3Name: "The Massacre of the Innocents"
    },
    {
        id: "13",
        name: "Vincent van Gogh",
        descriptionLess: "Vincent van Gogh (1853-1890) was born in Zundert in Brabant, where his father was a pastor. His uncles were art dealers and Vincent began his career working for them. After several years in the art trade, he worked as a lay preacher in England and later devoted time to missionary work in Belgium. In 1880, he resolved to become an artist.",
        descriptionMore: "At The Hague and Nuenen he painted still lifes, landscapes and scenes from village life in sombre colours. After a short period of study in Antwerp, Van Gogh moved to Paris. Influenced by Impressionism and Pointillism, he developed his characteristic style of separate streaks of paint and clear, vivid colours. In 1888, Van Gogh moved to Arles in the South of France. Mental illness led to several periods in hospital. Between these crises he continued to paint feverishly, until his death in 1890.",
        image1: "/images/Self-portrait-Gogh.jpg",
        image1Name: "Self-portrait",
        image2: "/images/De-aardappeleters-Gogh.jpg",
        image2Name: "De aardappeleters",
        image3: "/images/Farming-Village-at-Twilight-Gogh.jpg",
        image3Name: "Farming Village at Twilight"
    },
    {
        id: "14",
        name: "Jozef Israëls",
        descriptionLess: "Jozef Israëls (1824-1911) was born into a Dutch Jewish family. At the age of eleven he started painting and drawing lessons at Groningen’s Akademie Minerva. In 1842, he went to Amsterdam to study under painters Jan Adam Kruseman and Jan Willem Pieneman.",
        descriptionMore: "He later visited Paris, where he perfected his academic style of painting. He subsequently visited Germany, studying the German Romantic artists. Despite his training, Israëls did not devote his career to painting historical scenes. While recuperating from an illness at the Dutch fishing village of Zandvoort, he was appalled by the tragic lot of the fishermen and their families. His sober, restrained paintings depicting life in the fishing village earned him international fame. Critics compared his impasto brushwork, his warm colours and his use of chiaroscuro with the work of Rembrandt. Israëls taught numerous pupils, among them his son Isaac.",
        image1: "/images/Children-of-the-Sea-Israels.jpg",
        image1Name: "Children of the Sea",
        image2: "/images/Jewish-Wedding-Israels.jpg",
        image2Name: "Jewish Wedding",
        image3: "/images/The-Joy-of-Motherhood-Israels.jpg",
        image3Name: "The Joy of Motherhood"
    },
    {
        id: "15",
        name: "Isaac Israels",
        descriptionLess: "Jozef Israëls’s son, Isaac Israels (1865–1934) was raised on a diet of painting and travel. At thirteen, he entered art school in The Hague, where his prodigious talent was soon noticed.",
        descriptionMore: "In 1881, he began a painting that was purchased before it was completed by Hendrik Willem Mesdag. In 1886, Israels enrolled at Amsterdam’s Art Academy, where he was considered ‘too good’. Israels often spent the summer months with his father in Scheveningen, where he painted seaside scenes in bright colours. In Amsterdam, Israels spent much of his time with George Hendrik Breitner. Both were fascinated by the idea of portraying city life by capturing a passing moment in time. To convey the sense of a snapshot, they cropped their subjects abruptly. Israels was in Paris, London and briefly in the Dutch East Indies from 1903 to 1923. He then returned to The Hague and took over his father's studio. There he remained, producing impressionist paintings in light colours.",
        image1: "/images/A-Man-with-Three-Girls-Israels.jpg",
        image1Name: "A Man with Three Girls on a Bench in the Oosterpark in Amsterdam",
        image2: "/images/Young-Woman-Israels.jpg",
        image2Name: "Young Woman, Gazing at the Sea",
        image3: "/images/Dienstmeisje-met-kinderwagen-Israels.jpg",
        image3Name: "Dienstmeisje met kinderwagen op de Keizersgracht"
    },
    {
        id: "16",
        name: "Willem Bartel van der Kooi",
        descriptionLess: "Willem Bartel van der Kooi (1768-1836) was born in Augustinusga in Friesland, into a prominent, affluent family. At twelve, he was apprenticed to a local firm of painters and decorators. He developed his talent as an artist more or less independently.",
        descriptionMore: "He specialised in portraiture, although he also produced genre paintings. The French neo-Classical style clearly influenced his work. Van der Kooi taught numerous pupils and his impact on painting in Friesland in the 19th century was considerable. After winning a prize for genre painting in 1808, his work was in constant demand. In 1818, Van der Kooi was commissioned to paint portraits of Willem I and his consort. Van der Kooi’s growing reputation beyond Friesland is apparent in his appointment to various art academies in Amsterdam, Antwerp and Ghent.",
        image1: "/images/Jacobus-Scheltema-Kooi.jpg",
        image1Name: "Jacobus Scheltema (1767-1835), Historian",
        image2: "/images/Piano-Practice-Interrupted-Kooi.jpg",
        image2Name: "Piano Practice Interrupted",
        image3: "/images/The-Love-Letter-Kooi.jpg",
        image3Name: "The Love Letter"
    },
    {
        id: "17",
        name: "Jan Adam Kruseman",
        descriptionLess: "Artist Jan Adam Kruseman (1804-1862) of Haarlem was apprenticed to his uncle Cornelis Kruseman. He later studied at Brussels and Paris. In 1834-1836, he made a series of journeys to Germany, England and Scotland.",
        descriptionMore: "For a while, he lived in Driebergen, before returning to Haarlem in 1858. Kruseman painted historical, biblical and genre scenes, although mainly portraits. In all he received around five hundred commissions from aristocrats and wealthy commoners for portraits: one of the versatile artist’s many patrons was Willem I. Kruseman trained dozens of artists at his studio, among them his son Jan Theodoor as well as Jozef Israëls.",
        image1: "/images/Portrait-of-Alida-Christina-Assink-Kruseman.jpg",
        image1Name: "Portrait of Alida Christina Assink",
        image2: "/images/Portrait-of-William-II-Kruseman.jpg",
        image2Name: "Portrait of William II, King of the Netherlands",
        image3: "/images/Girl-Resting-Kruseman.jpg",
        image3Name: "Girl Resting"
    },
    {
        id: "18",
        name: "Willem van de Velde II",
        descriptionLess: "Willem van de Velde (1633-1707) was born in Leiden. His father - also called Willem van de Velde (hence I and II) – started life as a sailor and later became an artist for the Dutch navy. At fifteen, Van de Velde II was apprenticed to Simon de Vlieger, who specialised in atmospheric seascapes.",
        descriptionMore: "Van de Velde II’s early marines are generally tranquil, showing groups of fishing boats off the coast. After he and his father moved to England in 1672, Van de Velde II broadened his range. While he continued to paint marines, he made numerous portraits of individual vessels, such as royal yachts and battle ships. Van de Velde II was commissioned by the British king to paint various naval battles.",
        image1: "/images/The-Cannon-Shot-Velde.jpg",
        image1Name: "The Cannon Shot",
        image2: "/images/Ships-near-the-Coast-in-windy-Weather-Velde.jpg",
        image2Name: "Ships near the Coast in windy Weather",
        image3: "/images/A-Ship-on-the-High-Seas-Caught-by-Squall-Velde.jpg",
        image3Name: "A Ship on the High Seas Caught by a Squall, Known as ‘The Gust’"
    },
    {
        id: "19",
        name: "Frans Hals",
        descriptionLess: "Frans Hals (ca. 1582-1666), the son of a weaver, was born in Antwerp some time between 1581 and 1585. In his biography of Hals, Arnold Houbraken recounts how the family fled from the Spaniards in 1585 and settled in Haarlem.",
        descriptionMore: "There the young painter was apprenticed to Karel van Mander. Hals joined Haarlem’s artist guild in 1610. This enabled him to set up his own studio, and take on pupils and assistants, among them Judith Leyster. His younger brother Dirck Hals was probably also an apprentice. Hals was famous for his loose manner of painting, referred to by his contemporaries as 'the rough style'. This style has been both admired and reviled down the centuries. Hals tended to concentrate on portraits, and painted some superb civic guard pieces. He died in 1666 and was buried at St Bavo's, Haarlem’s principal church.",
        image1: "/images/Militia-Company-Codde.jpg",
        image1Name: "Militia Company of District XI under the Command of Captain Reynier Reael, Known as ‘The Meagre Company’",
        image2: "/images/A-Militiaman-Holding-a-Berkemeyer-Hals.jpg",
        image2Name: "A Militiaman Holding a Berkemeyer, Known as the ‘Merry Drinker’",
        image3: "/images/Portrait-of-a-Couple-Hals.jpg",
        image3Name: "Portrait of a Couple, Probably Isaac Abrahamsz Massa and Beatrix van der Laen"
    },
    {
        id: "20",
        name: "Salomon van Ruysdael",
        descriptionLess: "Salomon van Ruysdael (1600/03–1670) was called De Goyer until he and his brother Isaack changed their name to Ruysdael, after the castle near their father's native Blaricum. Salomon’s nephew Jacob was the only member of the family to spell their new name with an 'i': Ruisdael.",
        descriptionMore: "Salomon lived in Haarlem, and seems to have travelled widely in the Netherlands since he painted views of various Dutch cities. Although we no longer know who taught Salomon van Ruysdael landscape painting, his early work was clearly influenced by Esaias van de Velde, who painted vivid river views. In the 1630s, Ruysdael and Jan van Goyen developed a new, monochrome style.",
        image1: "/images/The-watering-place-Ruysdael.jpg",
        image1Name: "The watering place",
        image2: "/images/River-Landscape-with-Ferry-Ruysdael,.jpg",
        image2Name: "River Landscape with Ferry",
        image3: "/images/Sailing-vessels-on-a-inland-body-of-water-Ruysdael.jpg",
        image3Name: "Sailing vessels on a inland body of water"
    }
]


